kind: Deployment
apiVersion: apps/v1
metadata:
  name: dev-backend-deployment
  namespace: TaskPilot
  labels:
    app: TaskPilot-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: TaskPilot-backend
  template:
    metadata:
      labels: 
        app: TaskPilot-backend
    spec:
      containers:
      - name: TaskPilot-backend-container
        image: kushagr488/dev-backend:latest
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: dev-secret

