kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: taskpilot
  labels:
    app: taskpilot-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskpilot-backend
  template:
    metadata:
      labels: 
        app: taskpilot-backend
    spec:
      containers:
      - name: taskpilot-backend-container
        image: kushagr488/taskpilot-backend:latest
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: dev-secret

