kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: TaskPilot
spec:
  selector:
    app: TaskPilot-frontend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 5000
    nodePort: 30010
  type: NodePort
