kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  namespace: taskpilot
  labels:
    app: taskpilot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskpilot-frontend
  template:
    metadata:
      labels: 
        app: taskpilot-frontend
    spec:
      containers:
      - name: taskpilot-frontend-container
        image: kushagr488/taskpilot-frontend:latest
        ports:
        - containerPort: 5000
