kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: taskpilot
spec:
  clusterIP: None
  selector:
    app: postgres-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
