- name: Install the dependency tools
  hosts: role_application
  become: true

  vars:
      go_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

  tasks:
    - name: Install basic packages
      ansible.builtin.apt:
        name:
          - curl
          - dnsutils      # gives you `dig`
          - git
          - jq
          - unzip
        state: present
        update_cache: true

    # Configuration of aws cli   -----------------------------------------
    - name: Download Aws Cli
      ansible.builtin.get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip"
        dest: /tmp/awscli.zip
        mode: "0644"

    - name: Unzip the AWS CLI
      ansible.builtin.unarchive:
        src: /tmp/awscli.zip
        dest: /tmp
        remote_src: true
        creates: /tmp/aws/install        # If aws folder already exists then this step will be skipped automatically

    - name: Install the AWS CLI
      ansible.builtin.command:
        cmd: /tmp/aws/install --update
        creates: /usr/local/bin/aws       # If it already exists, Ansible skips the command.
    
    # Configuration of terraform 
    - name: Fetching current terraform version
      ansible.builtin.uri:
        url: https://checkpoint-api.hashicorp.com/v1/check/terraform
        return_content: true
      register: tf_release

    - name: Install Terraform
      ansible.builtin.unarchive:
        src: >-
          https://releases.hashicorp.com/terraform/{{ tf_release.json.current_version }}/terraform_{{ tf_release.json.current_version }}_linux_{{ go_arch }}.zip
        dest: /usr/local/bin
        remote_src: true
        mode: "0755"
        creates: /usr/local/bin/terraform
    
    # Configuration of kubectl -----------------------------------------------
    - name: Fetch the current kubectl version
      ansible.builtin.uri:
        url: https://dl.k8s.io/release/stable-1.34.txt
        return_content: true
      register: kubectl_release

    - name: Installl Kubectl 
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_release.content | trim  }}/bin/linux/{{ go_arch }}/kubectl"
        dest: /usr/local/bin/kubectl
        mode: "0755"

    # Configuration of helm 
    - name: Find the current Helm version
      ansible.builtin.uri:
        url: https://get.helm.sh/helm-latest-version
        return_content: true
      register: helm_release

    - name: Unarchieve helm
      ansible.builtin.unarchive:
        src: "https://get.helm.sh/helm-{{ helm_release.content | trim }}-linux-{{ go_arch }}.tar.gz"
        dest: /tmp
        remote_src: true
        creates: "/tmp/linux-{{ go_arch }}/helm"
    
    - name: Install Helm
      ansible.builtin.copy:
        src: "/tmp/linux-{{ go_arch }}/helm"
        dest: /usr/local/bin/helm
        mode: "0755"
        remote_src: true

    # Gh Cli configuration -----------------------
    - name: Fetching GH Cli latest version
      ansible.builtin.uri:
        url: "https://api.github.com/repos/cli/cli/releases/latest"
        return_content: true
      register: gh_release

    - name: Creating variables from file
      ansible.builtin.set_fact:
        gh_tag: "{{ gh_release.json.tag_name }}"
        gh_version: "{{ gh_release.json.tag_name | replace('v', '') }}"
    
    - name: Unpack the GitHub CLI
      ansible.builtin.unarchive:
        src: "https://github.com/cli/cli/releases/download/{{ gh_tag }}/gh_{{ gh_version }}_linux_{{ go_arch }}.tar.gz"
        dest: /tmp
        remote_src: true
        creates: "/tmp/gh_{{ gh_version }}_linux_{{ go_arch }}/bin/gh"

    - name: Install the GitHub CLI
      ansible.builtin.copy:
        src: "/tmp/gh_{{ gh_version }}_linux_{{ go_arch }}/bin/gh"
        dest: /usr/local/bin/gh
        mode: "0755"
        remote_src: true