name: secret_scanning
on:
  workflow_call:
    
jobs:
  cred_checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Check for Credential Leak
      uses: gitleaks/gitleaks-action@v3
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}